import QtQuick
import qs.Ui

// Generated by opal_c1.logo.qml_widget - edit the geometry there, not here.
BarWidget {
  id: root
  moduleName: "decomposer.overlay"

  implicitWidth: button.implicitWidth
  implicitHeight: button.implicitHeight

  WidgetButton {
    id: button
    anchors.fill: parent
    bar: root.bar
    hasVisualContent: true
    tooltipText: "decomposer"
    horizontalMargin: 7.5

    onPressed: function(which) {
      if (!root.bar) return
      root.bar.run("decomposer toggle")
    }

    Item {
      id: mark
      anchors.centerIn: parent
      // One grid cell per pixel, rounded so edges stay crisp at bar size.
      property int cell: Math.max(1, Math.round(button.fontSize / 16))
      width: cell * 16
      height: cell * 16

      Repeater {
        model: [[1,1], [2,1], [3,1], [7,1], [1,2], [2,2], [3,2], [4,2], [7,2], [8,2], [1,3], [2,3], [3,3], [4,3], [5,3], [7,3], [8,3], [9,3], [1,4], [2,4], [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [1,5], [2,5], [3,5], [4,5], [5,5], [6,5], [8,5], [9,5], [10,5], [11,5], [1,6], [2,6], [3,6], [4,6], [5,6], [6,6], [8,6], [9,6], [10,6], [11,6], [12,6], [1,7], [2,7], [3,7], [4,7], [5,7], [6,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7], [1,8], [2,8], [3,8], [4,8], [5,8], [6,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8], [1,9], [2,9], [3,9], [4,9], [5,9], [6,9], [8,9], [9,9], [10,9], [11,9], [12,9], [1,10], [2,10], [3,10], [4,10], [5,10], [6,10], [8,10], [9,10], [10,10], [11,10], [1,11], [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [1,12], [2,12], [3,12], [4,12], [5,12], [7,12], [8,12], [9,12], [1,13], [2,13], [3,13], [4,13], [7,13], [8,13], [1,14], [2,14], [3,14], [7,14]]
        delegate: Rectangle {
          x: modelData[0] * mark.cell
          y: modelData[1] * mark.cell
          width: mark.cell
          height: mark.cell
          color: button.foreground
        }
      }
    }
  }
}
